global.str_player_win="You win!"
global.str_bot_win="You lose"
global.str_draw = "Draw game!"
global.str_no_cards_player = "You lose - No cards to draw"
global.str_no_cards_bot = "You win - Opponent doesn't have a cards for draw"
